# Generated by Django 4.1.5 on 2023-01-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="t_sign",
            old_name="date",
            new_name="dateFrom",
        ),
        migrations.AddField(
            model_name="t_sign",
            name="dateTo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
