# Generated by Django 4.1.5 on 2023-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0002_rename_date_t_sign_datefrom_t_sign_dateto"),
    ]

    operations = [
        migrations.AddField(
            model_name="t_sign",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
